stages:
  - sonarqube-check

sonarqube-check:
  stage: sonarqube-check
  tags:
   - local 
  script: 
    - |
      docker run --rm ^
        -e SONAR_HOST_URL=%SONAR_HOST_URL% ^
        -e SONAR_TOKEN=%SONAR_TOKEN% ^
        -v "%cd%:/usr/src" ^
        sonarsource/sonar-scanner-cli ^
        -Dsonar.projectKey=S14P21E204 ^
        -Dsonar.sources=. ^
        -Dsonar.host.url=%SONAR_HOST_URL% ^
        -Dsonar.login=%SONAR_TOKEN%
  allow_failure: true
  only:
    - merge_requests
    - main
    - master