spring.application.name=srank
spring.config.import=optional:file:.env[.properties]

# Swagger server url
app.server.url=${SERVER_URL}

#
## JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_batch_fetch_size=100
#
## PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#
## GMS OPENAI
openai.base-url=${OPENAI_BASE_URL}
openai.api-key=${OPENAI_API_KEY}
#
# Redis - dev
spring.data.redis.host=redis-dev
spring.data.redis.port=6379
spring.data.redis.password=Ssafy1234!

# Redis - prod
spring.data.redis.host=redis-prod
spring.data.redis.port=6379
spring.data.redis.password=Ssafy1234!
## Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
#
## RabbitMQ
#spring.rabbitmq.host=${RABBITMQ_HOST}
#spring.rabbitmq.port=${RABBITMQ_PORT}
#spring.rabbitmq.username=${RABBITMQ_USERNAME}
#spring.rabbitmq.password=${RABBITMQ_PASSWORD}
#
## OAuth2
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#spring.security.oauth2.client.registration.google.scope=email,profile
#
## JWT
#jwt.secret=${JWT_SECRET}
#jwt.access-expiration=3600000
#jwt.refresh-expiration=604800000
#
## Privy
app.privy.app-id=${PRIVY_APP_ID:}
app.privy.issuer=${PRIVY_ISSUER:privy.io}
app.privy.verification-key=${PRIVY_VERIFICATION_KEY:}
#
## Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
# 
## Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
#
sentry.dsn=https://d2a80a9b5f10cc245b27e256ca3e4261@o4511017304850432.ingest.us.sentry.io/4511017351446528
sentry.environment=${SPRING_PROFILES_ACTIVE:local}
sentry.traces-sample-rate=1.0

#sentry.traces-sample-rate=0.2


dev.backdoor.token=${DEV_BACKDOOR_TOKEN:}
dev.backdoor.user-id=${DEV_BACKDOOR_USER_ID:0}